### PR TITLE
fix: fixed missing type file in package.json file entry

### PR DESCRIPTION
**Pull request by iceprosurface**

### CODE REVIEW

**Comment by chenxch** [comment]
@iceprosurface Maybe we can add a `types`, WDYT?

**Comment by iceprosurface** [comment]
I don't know why put index.d.ts outside, in my opinion, a better way would be to treat it as a type.ts and put it directly in src.
Then add `"type": "dist/index.d.ts",` to `package.json`
```diff
diff --git a/src/core/transform.ts b/src/core/transform.ts
index 7ba74ea..fd3f064 100644
--- a/src/core/transform.ts
+++ b/src/core/transform.ts
@@ -1,4 +1,4 @@
-import type {TransformOptions, TransformIndexHtmlConfig} from '../../index'
+import type {TransformOptions, TransformIndexHtmlConfig} from '../types'
 import {parse} from 'node-html-parser'
 import {replace, replaceImport, replaceInStringLiteral, replaceInTemplateElement, replaceSrc} from './utils'
 import {StringAsBytes, collectMatchingStrings, parseCode} from "./ast";
diff --git a/src/index.ts b/src/index.ts
index 41c31b6..7ed46f3 100644
--- a/src/index.ts
+++ b/src/index.ts
@@ -1,5 +1,5 @@
 import type { Plugin } from 'vite'
-import type { Options, TransformOptions } from '../index'
+import type { Options, TransformOptions } from './types'
 import { transformChunk, transformAsset, transformLegacyHtml, transformHtml } from './core/transform'
 
 export function dynamicBase(options?: Options): Plugin {
diff --git a/index.d.ts b/src/types.ts
similarity index 100%
rename from index.d.ts
rename to src/types.ts

```

**Comment by chenxch** [comment]
Agree, if you don't mind you can go ahead and do it.

**Comment by iceprosurface** [comment]
The update has been completed.

**Review by chenxch — APPROVED** [review]
LGTM.

**Pull request merged**
