### PR TITLE
Thanks for the effort to the repo, I made some super tiny enhancements for you to check

### PR DESCRIPTION
**Pull request by zhoujinfu**
1. setup simple unit tests with `vitest`.
2. change devDep `node-html-parser` as `dep` to fix module NOT FOUND errors. 
3. i met a `import.env.LEGACY` undefined errors in plugin.configResolved reproduce with 9f2ace00caac581380fd259e45325e8029eb9687 and fixed with aa2e90f43921dbae6d6bb6d0fd5265d29e54a964.

### CODE REVIEW

**Comment by chenxch** [comment]
This is all great, thank you so much for your contribution.

`tests\__snapshots__`  I think it should be ignored by default, what do you think?

**Comment by zhoujinfu** [comment]
Maybe we should keep the snapshots in repo and reviewed as part of your code review process. As quote from `jest` doc:
https://jestjs.io/docs/snapshot-testing#snapshot-testing-with-jest

> The snapshot artifact should be committed alongside code changes, and reviewed as part of your code review process. Jest uses [pretty-format](https://github.com/facebook/jest/tree/main/packages/pretty-format) to make snapshots human-readable during code review. On subsequent test runs, Jest will compare the rendered output with the previous snapshot. If they match, the test will pass. If they don't match, either the test runner found a bug in your code (in the <Link> component in this case) that should be fixed, or the implementation has changed and the snapshot needs to be updated.

**Comment by zhoujinfu** [comment]
I got another issue with the plugin in truly project. When we using `vite-plugin-dynamic-base` along with `vite-plugin-pwa`. It seems that we should both using the `publicPath` of `vite-plugin-dynamic-base` with `base` of `vite-plugin-pwa`. Any idea to go through it?

**Comment by chenxch** [comment]
Our snapshots will be a bit special. The content involves file directories. Everyone’s device is different, and the project storage address is different, so there will be different answers. At the time, I didn’t think it was a big problem.

**Comment by zhoujinfu** [comment]
> Our snapshots will be a bit special. The content involves file directories. Everyone’s device is different, and the project storage address is different, so there will be different answers. At the time, I didn’t think it was a big problem.

Well, i'll add shots to .gitignore for this PR

**Comment by chenxch** [comment]
> 我在真正的项目中遇到了另一个插件问题。当我们`vite-plugin-dynamic-base`与`vite-plugin-pwa`. 看来我们都应该使用`publicPath`of`vite-plugin-dynamic-base`和`base`of `vite-plugin-pwa`。有什么想法可以通过吗？

We are actually using base and publicpath as a match.

**Review by zhoujinfu — COMMENTED** [review]
Remove the __snapshots__/ and add `__snapshots__/` as git igored

**Comment by chenxch** [comment]
@zhoujinfu 方便提个issue 讨论下你那个问题么

**Comment by chenxch** [comment]
@zhoujinfu Thanks for your contribution, a new version has been released.

**Pull request merged**
